### ISSUE TITLE
git: clone from branch/commit/tag (-b) in the first place, with depth 1

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/acbs#14]
`acbs` currently does a full-ish clone and then checks out what it needs. That is inefficient af.

If any reusing of the clone is needed, just do a shallow fetch before checking out to what you need.

**Comment by jyhi** [comment]
@Artoria2e5 Also I propose if GITSRC is already cloned, then first try checking out GITCO, not doing git pull first. This helps boosting build procedures.

**Comment by Artoria2e5** [comment]
Uh I did mention doing a `fetch`?

**Comment by jyhi** [comment]
@Artoria2e5 Ouch, I did not pay attention to the second paragraph.

The case for me is: some large repositories that is actively developed (e.g. gcc, binutils) require a download every time I build them. However, my connection to these upstreams are often very unstable, so everytime git fails to fetch updates, my build fails, which is undesirable.

Thus, I think only fetch updates after checkout failure is a better choice.

**Comment by Artoria2e5** [comment]
Git now also has a "blobless" clone, `--filter=blob:none`. Blobs are fetched lazily at checkout. That might work with the way we do `--bare`.

**Comment by Artoria2e5** [comment]
e945ad5f1a5a1e1b7042b2695f8d5c41ea733afc is good enough for me, closing.
