### ISSUE TITLE
libarchive fails to load even if library installed

### ISSUE THREAD

**Issue by KexyBiscuit** [AOSC-Dev/acbs#16]
Even with libarchive installed (it's actually required by acbs in AOSC OS), the following code always executes.

https://github.com/AOSC-Dev/acbs/blob/16e000bb1cde82b58269f2b89f1cdc3c47a40860/acbs/src_process.py#L146-L147

**Comment by liushuyu** [comment]
Should be fixed somewhere between current stable and a16a38af7832f39e7b58d8c75411773701010002.
