### ISSUE TITLE
Naming and organization issues

### ISSUE THREAD

**Issue by gumblex** [AOSC-Dev/acbs#2]
As a Python project, we should observe several conventions:

* [x] `lib/acbs_*.py` should be `acbs/*.py`
* [x] Excessive usage of classes is not needed. General functions should be put at module level
* [x] Class names should be CapitalizedWords. `acbs_` prefix is also not needed

**Comment by gumblex** [comment]
should be fixed in https://github.com/AOSC-Dev/acbs/commit/cb92e32165c9853ddc7f5758ddbd32ce37c9fc8d

**Comment by MingcongBai** [comment]
A PR perhaps? Thanks.

**Comment by MingcongBai** [comment]
Thank you very much @gumblex
