### ISSUE TITLE
meta: architecture-related logic statements not processed by ACBS

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/acbs#7]
Originally reported as https://github.com/AOSC-Dev/aosc-os-abbs/issues/568 by @cthbleachbit .

```
if [[ "${CROSS:-$ARCH}" != arm* ]]; then
	VER=8u111b14
else
	if [[ "${CROSS:-$ARCH}" = armel ]]; then
		VER=8u101b13
	elif [[ "${CROSS:-$ARCH}" = arm64 ]]; then
		VER=8u111b16
	fi
fi

if [[ "${CROSS:-$ARCH}" = "arm64" ]]; then
	SRCTBL="https://repo.aosc.io/aosc-repacks/aarch64-java/openjdk-$VER.tar.xz"
elif [[ "${CROSS:-$ARCH}" = "armel" ]]; then
	SRCTBL="https://repo.aosc.io/aosc-repacks/aarch32-java/openjdk-$VER.tar.xz"
else
	SRCTBL="https://repo.aosc.io/aosc-repacks/openjdk-$VER.tar.xz"
fi
```

As found with `extra-java/openjdk` in https://github.com/AOSC-Dev/aosc-os-abbs, current state of ACBS with reading `spec` files could not produce the correct logical result - as seen in the example above. It is no longer possible to build a "special" version for `armel` with ACBS.

This issue is migrated here as suggested by @gumblex .

**Comment by MingcongBai** [comment]
The issue here, although partly resolved - is not done. The point is to have full Bash semantics in the `spec` file...

**Comment by liushuyu** [comment]
Fixed using an alternative solution (conditional `SRCS`).
